spring.application.name=contactpro
spring.datasource.url=jdbc:postgresql://localhost:5432/contactpro
spring.datasource.username=contactpro
spring.datasource.password=contactpro

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true